// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwtkkeyxjjqdyqovprhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dGtrZXl4ampxZHlxb3ZwcmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjM3OTgsImV4cCI6MjA2NDgzOTc5OH0.OVKUoZ-Y12kpdiu1G7Jw2YiypqsDUb33mXMDNIIhVNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});